version: "3.9"
services:
  db:
    build:
      context: .
      dockerfile: db/Dockerfile
    ports:
      - "5432:5432"
    tty: true
  webapp:
    build:
      dockerfile: webapp/Dockerfile
    ports:
      - "8004:8001"
    volumes:
      - .:/webapp
    depends_on:
      - db
    tty: true